import { cn } from "@/lib/utils";
import type { RoadmapPhase } from "@/types/analysis";

export function RevivalRoadmap({ phases }: { phases: RoadmapPhase[] }) {
  if (phases.length === 0) return <p className="surface p-5 text-sm text-muted-foreground">The roadmap is generated by the full analysis.</p>;
  return (
    <div className="space-y-3">
      <ol className="grid gap-4 lg:grid-cols-3">
        {phases.map((phase, i) => (
          <li key={phase.title} className="surface flex flex-col gap-3 p-5">
            <div className="flex items-center gap-3">
              <span className={cn("flex size-7 items-center justify-center rounded-full border text-xs font-mono", i === 0 ? "border-grave-green/40 text-grave-green" : i === 1 ? "border-grave-blue/40 text-grave-blue" : "border-grave-purple/40 text-grave-purple")}>{i + 1}</span>
              <h3 className="text-sm font-semibold">{phase.title}</h3>
            </div>
            <ul className="grid gap-2 text-sm text-muted-foreground">
              {phase.steps.map((step) => (
                <li key={step} className="flex items-start gap-2.5">
                  <span className="mt-1.5 size-1.5 shrink-0 rounded-sm border border-muted-foreground/50" />
                  {step}
                </li>
              ))}
            </ul>
          </li>
        ))}
      </ol>
      <p className="text-xs text-muted-foreground">Generated automatically from the findings above. Treat it as a starting point, not a plan.</p>
    </div>
  );
}
