import { Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

export function Section({ id, title, description, automatic, children, className }: { id: string; title: string; description?: string; automatic?: boolean; children: React.ReactNode; className?: string }) {
  return (
    <section id={id} aria-labelledby={`${id}-title`} className={cn("scroll-mt-24", className)}>
      <div className="mb-4 flex flex-wrap items-center gap-x-3 gap-y-1">
        <h2 id={`${id}-title`} className="text-xl font-semibold tracking-tight">
          {title}
        </h2>
        {automatic && (
          <Badge variant="outline" title="Generated by GitHub Graveyard from public GitHub data. An estimate, not a verdict.">
            <Sparkles /> Automatic analysis
          </Badge>
        )}
      </div>
      {description && <p className="-mt-2 mb-4 max-w-2xl text-sm text-muted-foreground">{description}</p>}
      {children}
    </section>
  );
}
